/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discord.manager.bot;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
// import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.cache.CacheFlag;
public class App {
    public static void main(String[] args) {
        JDABuilder builder = JDABuilder.createDefault("MTA3Mjc3MTgxNzk2NzcyNjY3Ng.G0ZuUu.sAmL7ieCdE1mMZFai3Fmtv4NpV6n6DPlzH2XVg");
        
        // Disable parts of the cache
        builder.disableCache(CacheFlag.MEMBER_OVERRIDES, CacheFlag.VOICE_STATE);
        // Enable the bulk delete event
        builder.setBulkDeleteSplittingEnabled(false);
        // Set activity (like "playing Something")
        builder.setActivity(Activity.watching("TV"));
        
        builder.build();
    }
}
